services:
  web:
    build: .
    container_name: django_app
    command: gunicorn toto.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./toto:/app/toto
      - static_volume:/app/toto/staticfiles
    expose:
      - "8000"
    environment:
      - DJANGO_ENV=DEBUG

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/staticfiles
    depends_on:
      - web

volumes:
  static_volume:
