services:
  web:
    build: .
    container_name: django_app
    command: gunicorn toto.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./toto:/app/toto
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./toto:/app/toto
    depends_on:
      - web
